#!/usr/bin/env python3

import os, sys, argparse, re

def retrieve_files(directory, file_list):
    for f in os.listdir(directory):
        match = re.search(r'^.*_[0-9]{4}-[0-9]{2}-[0-9]{2}\.tar\.(gz|bz2)$', f)
        if match:
            file_list.append(f)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--directory', help="Directory to backup and delete old files", required=True)
    args = parser.parse_args()

    if os.geteuid() != 0:
        print("You must execute this script as root", file=sys.stdout)
        sys.exit(1)

    directory = args.directory
    if not os.path.exists(directory):
        print("{0} does not exits".format(directory), file=sys.stdout)
        sys.exit(1)

    file_list = []
    retrieve_files(directory, file_list)

    sys.exit(0)

if __name__ == "__main__":
    main()
