#!/usr/bin/env python3

import os, sys, argparse, re, shutil

def retrieve_files(directory, file_list, regex):
    for f in os.listdir(directory):
        match = re.search(r"{0}".format(regex), f)
        if match:
            print("{0} found".format(f))
            file_list.append(os.path.join(directory, f))

def move_files(file_list, directory):
    for f in file_list:
        shutil.move(f, directory)
        print("{0} moved to {1}".format(f, directory))

def main():
    file_list = []
    parser = argparse.ArgumentParser()
    SHARE_DIR = "/media/share"

    parser.add_argument('-d', '--directory', help="Directory to backup and delete old files", required=True)
    args = parser.parse_args()

    if os.geteuid() != 0:
        print("You must execute this script as root", file=sys.stdout)
        sys.exit(1)

    directory = args.directory
    if not os.path.exists(directory):
        print("{0} does not exits".format(directory), file=sys.stdout)
        sys.exit(1)

    retrieve_files(directory, file_list, "^.*_[0-9]{4}-[0-9]{2}-[0-9]{2}\.tar\.(gz|bz2)$")
    move_files(file_list, "{0}/{1}".format(SHARE_DIR, os.getenv('USER')))

    sys.exit(0)

if __name__ == "__main__":
    main()
